pipeline:
  pipeline_type: delete_displace
visualization:
  visualize_layer: 1
  visualize_s: 1
  visualize_delete: 0
  visualize_select: 0
  visualize_move: 0
data:
  filename: ../examples/z cubic/SrTiO3/SrTiO3.data
  format: lammps-data
  atom_style: atomic
  lattice: 7
layerization:
  layer_direction_vector: [1, 0, 0]
s_plane:
  s_center_point: [168.5, 170, 23]
  s_type: rectangle
  s_length: 170
  s_width: 48
  s_init_vertical_axis: 0
  s_init_direction_vector: [1, 0, 0]
delete:
  burgers_vector_fraction: 1
  burgers_vector_direction: [1, 1, 0]
select:
  layer_range: [10, 150]
moving:
  move_direction_vector: [1, 0, 0]
  move_step: 1.414