pipeline:
  pipeline_type: displace
visualization:
  visualize_layer: 0
  visualize_s: 1
  visualize_select: 0
  visualize_move: 0
data:
  filename: ../examples/fcc/rotation_loop/Ni.data
  format: lammps-data
  atom_style: atomic
  lattice: 3.556
layerization:
  layer_direction_vector: [0, 0, 1]
s_plane:
  s_center_point: [0.63, 1.03, 0.36]
  s_type: loop
  s_num_points: 48
  s_radius: 10
  s_init_vertical_axis: 2
  s_init_direction_vector: [0, 0, 1]
  s_direction_vector: [0, 1, 2.8286]
moving:
  move_direction_vector: [0, 1, 0]
  move_step: 0.408