pipeline:
  pipeline_type: displace
visualization:
  visualize_layer: 0
  visualize_s: 0
  visualize_select: 0
  visualize_move: 
data:
  filename: ../examples/fcc/screw_dislocation/NiCoCr.data
  format: lammps-data
  atom_style: atomic
  lattice: 3.556
layerization:
  layer_direction_vector: [0, 1, 0]
s_plane:
  s_center_point: [-70, 25, 0]
  s_type: rectangle
  s_length: 140
  s_width: 1000
moving:
  move_direction_vector: [0, 0, 1]
  move_step: 0.707